servers:
  - name: playwright
    type: node
    path: "./playwright-mcp"
    args:
      # - "--headless"
      - "--no-sandbox"
      - "--isolated"
      # - "--executable-path"
      # - "/ms-playwright/chromium_headless_shell-1178/chrome-linux/headless_shell"
    env:
      PLAYWRIGHT_HEADLESS: "true"

defaults:
  python_env_path: 
  node_command: npx